### PR TITLE
added citation

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**
Hej EB, 

I will be citing this work in an upcoming paper on DaCy. I have added the citation I intend to use, but feel free to change it if you feel like it doesn't fit. I will change mine accordingly. I extracted the authors from the commit history which I realize isn't always representative.

### CODE REVIEW

**Comment by smaakage85** [comment]
Hej Kenneth! Tak for dit bidrag. Hvordan skal jeg skrive, hvis jeg ønsker at tilføje Lukas Nielsen som medforfatter?

Bedste hilsner
Lars

**Comment by KennethEnevoldsen** [comment]
Ville nok gøre det således:
```
@inproceedings{nerda,
   title = {NERDA},
   author = {Kjeldgaard, Lars and Nielsen, Lukas},
   year = {2020},
   publisher = {{GitHub}},
   url = {https://github.com/ebanalyse/NERDA}
 }
```

**Comment by smaakage85** [comment]
Tak @KennethEnevoldsen 

Jeg tilføjer :)

**Comment by smaakage85** [comment]
opdateret med dine ændringer

**Pull request closed without merging**
